
name = "medical-triage-simulator"
compatibility_date = "2025-05-07"

# Configure your site
[site]
bucket = "./dist"

# Routes all requests to the index.html file to enable client-side routing
[site.upload]
format = "service-worker"

[build]
command = "npm run build" 
[build.upload]
format = "service-worker"

